# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 032edb8e0317d3f8b6c90aa4935fd5ebe0ae5703ee0cca76d43d0684290fa87a25b7cae974ecd8ddf328c3f59cd6eef9a81f6929b5d32c4e0ef148ee9ab2e5c9

test:
  secret_key_base: 82109f935472776644b8ae8f285aa59bc278b6ef2d65f4fb04abf46740ab2cc6f0dc13bdf171a4ba8a7441f30310e26572890fb8119a1db1841de725d89e7ddd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
